Repository luangalindo1/projeto_GerSw_SWT2, pull requests merged in 2025-03, with the labels that each got.

#14 Implementa testes para as conversões de QR Code, com pytests
  qrcode_converter.py
  tests/test_qrcode.py
Labels: enhancement

#31 Feature: Implementa interface básico pras funções do QR Code utilizando TKinter
  conversor.py
Labels: enhancement

#33 UI Completa + pequeno ajuste no yml
  .github/workflows/main_CI.yml
  .gitignore
  conversor.py
  currency_converter.py
  dockerfile
  requirements.txt
Labels: enhancement

#34 Inserção dos ultimos topicos do relatório
  RELATÓRIO.md
Labels: documentation

#35 Detalhes adicionais sobre o conversor de moedas
  README.md
Labels: documentation

#36 Develop/dockerfile
  README.md
  dockerfile
Labels: documentation, enhancement
